### ISSUE TITLE
migration always fails with "Error: Inconsistent dependency lock file"

### ISSUE THREAD

**Issue by grayzu** [Azure/azapi2azurerm#12] opened 2022-02-02 19:41 UTC
### Versions
Latest build of the migration tool.

### Operating System

![image](https://user-images.githubusercontent.com/2914336/152223930-6f70cf74-5577-4152-abff-73d2594cefc8.png)

### Terraform Version

```
Terraform v1.1.4 on darwin_amd64
```

### Steps To Reproduce

1. Run command azurerm-restapi-to-azurerm migrate
2. See error
![image](https://user-images.githubusercontent.com/2914336/152223745-94d648ca-9466-48b4-885c-e9b0804a7f9d.png)

### Expected Behavior
Migrate should succeed.

### Actual Behavior
Migrate fails with above error.

### Additional context
I have added version information to the provider block for all providers, deleted all state and lock files, rerun init and still get the error. Would this have anything to do with mixing the versions of Terraform?

**Comment by ms-henglu** [comment] 2022-08-02 05:04
The cause is `terraform init` command failed when there's an unreleased provider in use, now `azapi` has been released, so we can close this issue.

**Closed by ms-henglu** 2022-08-02 05:04 UTC
Labels: bug
